# you will find the build script
# for the image in ci/docker/Dockerfile
image: zauberstuhl/ganggo-ci:1.9-stretch
services:
- postgres:latest
variables:
  POSTGRES_DB: ganggo
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  UPDATE_CHANNEL: alpha
stages:
- test
- build
- deploy
before_script:
- export VERSION=$(git tag -l --sort=-v:refname |head -n1)
- export PROJECT_PATH=$GOPATH/src/git.feneas.org/ganggo
- mkdir -p $PROJECT_PATH bin
- rm -r $GOPATH/bin
- ln -s $(pwd) $PROJECT_PATH/ganggo
- ln -sf $(pwd)/bin $GOPATH/bin
- cd $PROJECT_PATH/ganggo
linux:test:
  artifacts:
    expire_in: "1 hour"
    paths:
    - vendor/
    - node_modules/
    - bin/
  stage: test
  script:
  - make install
  - make test
  except:
  - master
linux:amd64:
  artifacts:
    expire_in: "1 hour"
    paths:
    - updater.*.bin
  stage: build
  script:
  - export GOARCH=amd64
  - export GOOS=linux
  - make release
  dependencies:
  - linux:test
windows:amd64:
  artifacts:
    expire_in: "1 hour"
    paths:
    - updater.*.bin
  stage: build
  script:
  - export CGO_ENABLED=1
  - export CXX=x86_64-w64-mingw32-g++
  - export CC=x86_64-w64-mingw32-gcc
  - export GOARCH=amd64
  - export GOOS=windows
  - make release
  dependencies:
  - linux:test
  only:
  - /^v[\d\.]+-\w.*$/
windows:386:
  artifacts:
    expire_in: "1 hour"
    paths:
    - updater.*.bin
  stage: build
  script:
  - export CGO_ENABLED=1
  - export CXX=i686-w64-mingw32-g++
  - export CC=i686-w64-mingw32-gcc
  - export GOARCH=386
  - export GOOS=windows
  - make release
  dependencies:
  - linux:test
  only:
  - /^v[\d\.]+-\w.*$/
linux:arm:7:
  artifacts:
    expire_in: "1 hour"
    paths:
    - updater.*.bin
  stage: build
  script:
  - export CGO_ENABLED=1
  - export CC=arm-linux-gnueabihf-gcc
  - export GOARCH=arm
  - export GOOS=linux
  - export GOARM=7
  - make release
  dependencies:
  - linux:test
  only:
  - /^v[\d\.]+-\w.*$/
deploy artifacts to bintray:
  before_script:
  - export VERSION=$(git tag -l --sort=-v:refname |head -n1)
  stage: deploy
  script:
  - bash ci/scripts/bintray.sh
  dependencies:
  - linux:amd64
  - windows:amd64
  - windows:386
  - linux:arm:7
  only:
  - /^v[\d\.]+-\w.*$/
