# you will find the build script
# for the image in ci/docker/Dockerfile
image: zauberstuhl/ganggo-ci:1.9-stretch
services:
- postgres:latest
variables:
  POSTGRES_DB: ganggo
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  UPDATE_CHANNEL: alpha
stages:
- test
- packages
- deploy
cache:
  key: "ganggo-$CI_PIPELINE_ID"
  paths:
  - vendor
  - node_modules
before_script:
- export VERSION=$(git describe --abbrev=0 --tags)
- mkdir -p $GOPATH/src/github.com/ganggo
- ln -s $(pwd) $GOPATH/src/github.com/ganggo/ganggo
- if [ ! -d "vendor" ]; then make install; fi
running unit tests:
  stage: test
  script:
  - make test
building with GOARCH=amd64 GOOS=linux:
  stage: packages
  script:
  - export GOARCH=amd64
  - export GOOS=linux
  - make release
building with GOARCH=amd64 GOOS=windows:
  stage: packages
  script:
  - export CGO_ENABLED=1
  - export CXX=x86_64-w64-mingw32-g++
  - export CC=x86_64-w64-mingw32-gcc
  - export GOARCH=amd64
  - export GOOS=windows
  - make release
building with GOARCH=386 GOOS=windows:
  stage: packages
  script:
  - export CGO_ENABLED=1
  - export CXX=i686-w64-mingw32-g++
  - export CC=i686-w64-mingw32-gcc
  - export GOARCH=386
  - export GOOS=windows
  - make release
building with GOARCH=arm GOOS=linux GOARM=7:
  stage: packages
  script:
  - export CGO_ENABLED=1
  - export CC=arm-linux-gnueabihf-gcc
  - export GOARCH=arm
  - export GOOS=linux
  - export GOARM=7
  - make release
deploy update packages:
  stage: deploy
  artifacts:
    name: "$UPDATE_CHANNEL"
    expire_in: "1 day"
    paths:
    - updater.*.bin
  script:
  - bash -c true
  when: manual
