# you will find the build script for the image
# in git.feneas.org:ganggo/docker.git
image: ganggo/ganggo-ci:1.9-stretch
services:
- postgres:latest
- mysql:latest
variables:
  POSTGRES_DB: ganggo
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  UPDATE_CHANNEL: alpha
stages:
- install
- test
- build
- deploy
- review
before_script:
- export VERSION=$(git tag -l --sort=-v:refname |head -n1)
- export PROJECT_PATH=$GOPATH/src/git.feneas.org/ganggo
- mkdir -p $PROJECT_PATH bin
- rm -r $GOPATH/bin
- ln -s $(pwd) $PROJECT_PATH/ganggo
- ln -sf $(pwd)/bin $GOPATH/bin
- cd $PROJECT_PATH/ganggo
install:
  artifacts:
    expire_in: "1 hour"
    paths:
    - vendor/
    - node_modules/
    - bin/
  stage: install
  script:
  - make install
  except:
  - master
  - develop
linux:test:psql:
  stage: test
  script:
  - bash ci/scripts/change_database.sh postgres
  - make test
  dependencies:
  - install
  except:
  - master
  - develop
linux:test:mysql:
  stage: test
  script:
  - bash ci/scripts/change_database.sh mysql
  - make test
  dependencies:
  - install
  except:
  - master
  - develop
linux:amd64:
  artifacts:
    expire_in: "1 hour"
    paths:
    - updater.*.bin
  stage: build
  script:
  - export GOARCH=amd64
  - export GOOS=linux
  - make release
  dependencies:
  - install
  except:
  - master
  - develop
windows:amd64:
  artifacts:
    expire_in: "1 hour"
    paths:
    - updater.*.bin
  stage: build
  script:
  - export CGO_ENABLED=1
  - export CXX=x86_64-w64-mingw32-g++
  - export CC=x86_64-w64-mingw32-gcc
  - export GOARCH=amd64
  - export GOOS=windows
  - make release
  dependencies:
  - install
  only:
  - /^v[\d\.]+-\w.*$/
windows:386:
  artifacts:
    expire_in: "1 hour"
    paths:
    - updater.*.bin
  stage: build
  script:
  - export CGO_ENABLED=1
  - export CXX=i686-w64-mingw32-g++
  - export CC=i686-w64-mingw32-gcc
  - export GOARCH=386
  - export GOOS=windows
  - make release
  dependencies:
  - install
  only:
  - /^v[\d\.]+-\w.*$/
linux:arm:7:
  artifacts:
    expire_in: "1 hour"
    paths:
    - updater.*.bin
  stage: build
  script:
  - export CGO_ENABLED=1
  - export CC=arm-linux-gnueabihf-gcc
  - export GOARCH=arm
  - export GOOS=linux
  - export GOARM=7
  - make release
  dependencies:
  - install
  only:
  - /^v[\d\.]+-\w.*$/
deploy artifacts to bintray:
  before_script:
  - export VERSION=$(git tag -l --sort=-v:refname |head -n1)
  stage: deploy
  script:
  - bash ci/scripts/bintray.sh
  dependencies:
  - linux:amd64
  - windows:amd64
  - windows:386
  - linux:arm:7
  only:
  - /^v[\d\.]+-\w.*$/
trigger other pipelines:
  before_script:
  - export VERSION=$(git tag -l --sort=-v:refname |head -n1)
  stage: review
  script:
  # ID 99 https://git.feneas.org/ganggo/docker
  - curl -X POST -F "token=$CI_JOB_TOKEN" -F "ref=master" -F "variables[GVERSION]=$VERSION" https://git.feneas.org/api/v4/projects/99/trigger/pipeline
  # XXX trigger updating documentation
  dependencies:
  - deploy artifacts to bintray
  only:
  - /^v[\d\.]+-\w.*$/
